export const FETCH_PROCESSES_SUCCESS = 'FETCH_PROCESSES_SUCCESS';
export const ADD_PROCESS = 'ADD_PROCESS';
export const ADD_PROCESS_SUCCESS = 'ADD_PROCESS_SUCCESS';
export const ADD_PROCESS_FAILURE = 'ADD_PROCESS_FAILURE';
export const DEL_PROCESS_SUCCESS = 'DEL_PROCESS_SUCCESS';
export const EDIT_PROCESS = 'EDIT_PROCESS';
export const EDIT_PROCESS_SUCCESS = 'EDIT_PROCESS_SUCCESS';
export const EDIT_PROCESS_FAILURE = 'EDIT_PROCESS_FAILURE';

export const FETCH_STAGES_SUCCESS = 'FETCH_STAGES_SUCCESS';
export const ADD_STAGE = 'ADD_STAGE';
export const ADD_STAGE_SUCCESS = 'ADD_STAGE_SUCCESS';
export const EDIT_STAGE = 'EDIT_STAGE';
export const EDIT_STAGE_SUCCESS = 'EDIT_STAGE_SUCCESS';
export const EDIT_STAGE_FAIL = 'EDIT_STAGE_FAIL';
export const DEL_STAGE_SUCCESS = 'DEL_STAGE_SUCCESS';

export const FETCH_FOLLOWS_SUCCESS = 'FETCH_FOLLOWS_SUCCESS';
export const ADD_FOLLOW_SUCCESS = 'ADD_FOLLOW_SUCCESS';
export const DEL_FOLLOW_SUCCESS = 'DEL_FOLLOW_SUCCESS';

export const ADD_PERFORM_SUCCESS = 'ADD_PERFORM_SUCCESS';
export const FETCH_PERFORMS_SUCCESS = 'FETCH_PERFORMS_SUCCESS';
export const DEL_PERFORM_SUCCESS = 'DEL_PERFORM_SUCCESS';

export const ADD_OPTION_SUCCESS = 'ADD_OPTION_SUCCESS';
export const DEL_OPTION_SUCCESS = 'DEL_OPTION_SUCCESS';
export const FETCH_OPTIONS_SUCCESS = 'FETCH_OPTIONS_SUCCESS';
export const ADD_OPTION_FAILURE = 'ADD_OPTION_FAILURE';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const DEL_TASK_SUCCESS = 'DEL_TASK_SUCCESS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const MOVE_TASK_SUCCESS = 'MOVE_TASK_SUCCESS';

export const SET_SIDEBAR = 'SET_SIDEBAR';
