export const pos = [
    { level: 0, value: 1, label: 'SINH VIÊN THỰC TẬP' },
    { level: 1, value: 9, label: 'NHÂN VIÊN PART TIME' },
    { level: 2, value: 2, label: 'NHÂN VIÊN THỬ VIỆC' },
    { level: 3, value: 3, label: 'NHÂN VIÊN CHÍNH THỨC' },
    { level: 4, value: 20, label: 'NHÓM PHÓ' },
    { level: 5, value: 4, label: 'TRƯỞNG NHÓM' },
    { level: 6, value: 12, label: 'PHÓ TỔ TRƯỞNG' },
    { level: 7, value: 13, label: 'TỔ TRƯỞNG' },
    { level: 8, value: 10, label: 'PHÓ BAN DỰ ÁN' },
    { level: 9, value: 11, label: 'TRƯỞNG BAN DỰ ÁN' },
    { level: 10, value: 5, label: 'PHÓ TRƯỞNG PHÒNG' },
    { level: 11, value: 6, label: 'TRƯỞNG PHÒNG' },
    { level: 12, value: 7, label: 'PHÓ GIÁM ĐỐC' },
    { level: 13, value: 8, label: 'GIÁM ĐỐC' },
    { level: 14, value: 14, label: 'PHÓ TỔNG GIÁM ĐỐC' },
    { level: 15, value: 16, label: 'TỔNG GIÁM ĐỐC' },
    { level: 16, value: 22, label: 'PHÓ TỔNG GIÁM ĐỐC TẬP ĐOÀN' },
    { level: 17, value: 21, label: 'TỔNG GIÁM ĐỐC TẬP ĐOÀN' },
    { level: 18, value: 17, label: 'THÀNH VIÊN HỘI ĐỒNG QUẢN TRỊ' },
    {
      level: 19,
      value: 18,
      label: 'PHÓ CHỦ TỊCH HỘI ĐỒNG QUẢN TRỊ',
    },
    {
      level: 20,
      value: 19,
      label: 'CHỦ TỊCH HỘI ĐỒNG QUẢN TRỊ',
    },
    {
      level: 21,
      value: 0,
      label: 'CHỨC VỤ KHÁC',
    },
  ];
  